### ISSUE TITLE
团辅xml

### ISSUE THREAD

**Issue by Dragoon9827** [553469159/FFXIV_Auxiliary_Tools#1]
能不能把自己的团辅也放在触发里面 或者说怎么设置

**Comment by Souma-Sumire** [comment]
- 取消每一个技能的**队伍职业过滤** （会变成全部显示）（没办法他这个过滤不太好用，如果2个过滤一起勾选就是AND而不是OR）
- 将**Get巨龙视线**的正则修改为：`<mex> gains the effect of (巨龙左眼|竜の左眼|Left Eye|巨龙右眼|竜の右眼|Right Eye) from`
应该就可以了

**Comment by Dragoon9827** [comment]
好的 谢谢 我尝试一下
