### ISSUE TITLE
obs自动录制

### ISSUE THREAD

**Issue by Twopie** [553469159/FFXIV_Auxiliary_Tools#9]
如何实现倒计时20s开始录制 结束战斗20s后结束录制

**Comment by Souma-Sumire** [comment]
开始条件改为
`^.{14} 00:(?:00b9|0139):距离战斗开始还有2.秒！ （`
结束动作增加20000ms延迟
![img](https://i.loli.net/2021/02/07/bCdnM3uXSH5Vo9s.png)
